name = "github-docs-worker"
main = "src/index.js"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "github-docs-db"
database_id = "e6471e75-625d-49cc-82ea-efae46a5b312"

[[secrets_store_secrets]]
binding     = "DOCS_WEBHOOK_TOKEN"
secret_name = "DOCS_WEBHOOK_TOKEN"
store_id    = "2556bcd9458349f6b4ff2a3fc93bdba1"

[[secrets_store_secrets]]
binding     = "GITHUB_TOKEN"
secret_name = "GITHUB_TOKEN"
store_id    = "2556bcd9458349f6b4ff2a3fc93bdba1"

[observability]
enabled = true

[vars]
FRONTEND_URL = "https://docs.stellarglobalsupplies.com"